{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "wordpress-app.fullname" . }}-nginx
  labels:
    {{- include "wordpress-app.labels" . | nindent 4 }}
    component: nginx
spec:
  selector:
    matchLabels:
      {{- include "wordpress-app.selectorLabels" . | nindent 6 }}
      component: nginx
  endpoints:
  - port: metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    path: /metrics
{{- end }}
