apiVersion: v2
name: monitoring
description: Prometheus and Grafana monitoring stack for WordPress
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - prometheus
  - grafana
  - monitoring
  - alerting
dependencies:
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: grafana
    version: "7.0.8"
    repository: "https://grafana.github.io/helm-charts"
maintainers:
  - name: Somil Rathore
    email: somil@example.com
